name: 'Get and cache dependencies'
description: 'Get the depencies (via npm) and cache them'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with: 
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/02 Starting Project/package-lock.json') }}
    - name: Instal dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
