name: 'Get and cache dependencies'
description: 'Get the depencies (via npm) and cache them'
inputs:
  caching:
    description: 'Wheather to cache dependencies or not'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with: 
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/02 Starting Project/package-lock.json') }}
    - name: Instal dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        cd "Code/02 Basics/02 Starting Project"
        npm ci
      shell: bash
