name: Test and deploy project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses:  actions/checkout@v3
      - name: Load and cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Run Tests
        run: |
             cd "Code/02 Basics/02 Starting Project"
             npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses:  actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
              cd "Code/02 Basics/02 Starting Project"
              npm ci
      - name: Build Project
        run: |
              cd "Code/02 Basics/02 Starting Project"
              npm run build
      - name: Deploy
        run: echo "Deploying ..."
  information: 
    runs-on: ubuntu-latest
    steps:
      - name: Run cutom action
        uses: .github/actions/deploy-s3-javascript