name: Test and deploy project
on: [push, workflow_dispatch]
env:
  MONGODB_DB_NAME: gha-demo
  
jobs:
  reusable:
    uses: ./.github/workflows/reusable.yml
    with: 
      artifact-name: apple
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses:  actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: |
              cd "Code/02 Basics/02 Starting Project"
              npm ci
      - name: Run Tests
        run: |
             cd "Code/02 Basics/02 Starting Project"
             npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps: 
      - name: Get code
        uses:  actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
              cd "Code/02 Basics/02 Starting Project"
              npm ci
      - name: Build Project
        run: |
              cd "Code/02 Basics/02 Starting Project"
              npm run build
      - name: Publish JS filename
        id: publish
        run: find "Code/02 Basics/02 Starting Project/dist/" -type f -name '*.js' -exec sh -c 'echo "script-file={}" >> "$GITHUB_OUTPUT"' \;    
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
              Code/02 Basics/02 Starting Project/dist
              Code/02 Basics/02 Starting Project/package.json
      - name: Deploy
        run: echo "Deploying ..."
  publish:
    needs: deploy
    runs-on: ubuntu-latest
    steps: 
      - name: Output file name
        run: echo "${{ needs.deploy.outputs.script-file }}"
